#!/usr/bin/env bash
# Regenerate the API types from the vendored OpenAPI spec.
#
# Pinned tool: openapi-typescript 7.13.0. The pin lives in package.json's
# devDependencies AND in the message below; `npx --no-install` is deliberate,
# so this script uses the version the lockfile installed rather than silently
# resolving a newer one from the registry.
#
# What this writes is ONE file of TYPES — `src/_generated/schema.d.ts`. There
# is no generated runtime here, unlike the Python client's vendored package:
# openapi-typescript emits declarations only, and `openapi-fetch` reads them
# at compile time to type the paths, the query parameters and the response
# bodies of the calls in src/faxes.ts. Nothing generated is on the wire, and
# nothing generated crosses the public boundary — see src/models.ts.
#
# The file IS committed, so a spec-sync diff stays reviewable in a PR.
set -euo pipefail

GENERATOR_VERSION="7.13.0"

cd "$(dirname "${BASH_SOURCE[0]}")/.."

SPEC_PATH="spec/openapi.yaml"
DEST="src/_generated/schema.d.ts"

if [[ ! -f "${SPEC_PATH}" ]]; then
  echo "generate.sh: ${SPEC_PATH} not found — vendor the spec first" >&2
  exit 1
fi

mkdir -p "$(dirname "${DEST}")"

npx --no-install openapi-typescript "${SPEC_PATH}" -o "${DEST}"

# A banner the generator does not write for itself, prepended so anybody who
# opens the file knows it is overwritten rather than edited.
BANNER=$(cat <<EOF
/**
 * Generated by openapi-typescript ${GENERATOR_VERSION}
 * Source spec: ${SPEC_PATH}
 * Regenerate with: scripts/generate.sh
 * Do not hand-edit this file — it is overwritten on the next run.
 */
EOF
)
printf '%s\n%s\n' "${BANNER}" "$(cat "${DEST}")" > "${DEST}.tmp"
mv "${DEST}.tmp" "${DEST}"

echo "generate.sh: wrote ${DEST} from openapi-typescript ${GENERATOR_VERSION}"
